//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFileModule.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchFileModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   検索結果をクリアしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearResultsMessage {
            get {
                return ResourceManager.GetString("ClearResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイル名をコピーしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyFileNameMessage {
            get {
                return ResourceManager.GetString("CopyFileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイルを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDeleteMessage {
            get {
                return ResourceManager.GetString("FileDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OccurExceptionMessage {
            get {
                return ResourceManager.GetString("OccurExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を検索中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingDirectoryMessage {
            get {
                return ResourceManager.GetString("SearchingDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingErrorMessage {
            get {
                return ResourceManager.GetString("SearchingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイルが見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingResultMessage {
            get {
                return ResourceManager.GetString("SearchingResultMessage", resourceCulture);
            }
        }
    }
}
